name: VTK-9.5.2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  shared:
    uses: sanguinariojoe/vtk-builds/.github/workflows/builder.yml@main
    with:
      version_major: 9
      version_minor: 5
      version_patch: 2
      shared: true
    secrets: inherit
  static:
    uses: sanguinariojoe/vtk-builds/.github/workflows/builder.yml@main
    with:
      version_major: 9
      version_minor: 5
      version_patch: 2
      shared: false
    secrets: inherit
